# -*- coding: utf-8 -*-
"""共享数据: 结构体/FB表/con变量 等通用内容 (跨工程复用, 不进 JSON 规格单)."""

# 结构体定义 (成员, 类型, 注释)
STRUCTURES = {
    'AxisControlData': [
        ('PowerEnable', 'BOOL', '轴使能'),
        ('Stop', 'BOOL', '轴停止(立即,优先级最高)'),
        ('Reset', 'BOOL', '故障复位(上升沿)'),
        ('Home', 'BOOL', '回零启动(上升沿)'),
        ('JogForward', 'BOOL', '正向点动'),
        ('JogBackward', 'BOOL', '反向点动'),
        ('Jogvelocity', 'REAL', '点动速度'),
        ('JogAcceleration', 'REAL', '点动加速度'),
        ('JogDeceleration', 'REAL', '点动减速度'),
        ('Absolute_Execute', 'BOOL', '绝对定位启动(上升沿)'),
        ('Absolute_Position', 'REAL', '目标位置'),
        ('Absolute_Velocity', 'REAL', '定位速度'),
        ('Absolute_Acceleration', 'REAL', '定位加速度'),
        ('Absolute_Deceleration', 'REAL', '定位减速度'),
    ],
    'ST_AxisPower': [
        ('Status', 'BOOL', '轴使能状态'),
        ('Busy', 'BOOL', '使能执行中'),
        ('Active', 'BOOL', '使能激活'),
        ('Error', 'BOOL', '使能故障'),
        ('ErrorID', 'DINT', '使能故障码'),
    ],
    'ST_MC_Status': [
        ('Done', 'BOOL', '动作完成'),
        ('Busy', 'BOOL', '动作执行中'),
        ('Active', 'BOOL', '动作激活'),
        ('CommandAborted', 'BOOL', '命令中止'),
        ('Error', 'BOOL', '动作故障'),
        ('ErrorID', 'DINT', '动作故障码'),
    ],
    'AxisStatusData': [
        ('Power', 'ST_AxisPower', '使能状态子结构'),
        ('Stop', 'ST_MC_Status', '停止状态子结构'),
        ('Reset', 'ST_MC_Status', '复位状态子结构'),
        ('Home', 'ST_MC_Status', '回零状态子结构'),
        ('Jog', 'ST_MC_Status', '点动状态子结构'),
        ('MoveAbsolute', 'ST_MC_Status', '绝对定位状态子结构'),
        ('MoveRelative', 'ST_MC_Status', '相对定位状态子结构'),
        ('MoveVelocity', 'ST_MC_Status', '速度模式状态子结构'),
        ('Halt', 'ST_MC_Status', '暂停状态子结构'),
        ('Position', 'REAL', '实际位置'),
        ('Velocity', 'REAL', '实际速度'),
        ('Torque', 'REAL', '实际转矩'),
        ('AxisState', 'DINT', '轴状态机(0断/1错误停/2停止中/3静止/4离散/5连续/6同步/7回零)'),
        ('Error', 'BOOL', '轴故障'),
        ('AxisErrorID', 'DINT', '轴故障码'),
        ('ReturnHomeDone', 'BOOL', '回零完成'),
        ('PowerStatus', 'BOOL', '使能状态'),
        ('LimitPos', 'BOOL', '正向限位'),
        ('LimitNeg', 'BOOL', '负向限位'),
    ],
    'ST_Stepper': [
        ('ManForward', 'BOOL', '手动正向'),
        ('ManBackward', 'BOOL', '手动反向'),
        ('AutoForward', 'BOOL', '自动正向'),
        ('AutoBackward', 'BOOL', '自动反向'),
        ('Reset', 'BOOL', '故障复位'),
        ('Stop', 'BOOL', '停止'),
        ('Forward', 'BOOL', '正向输出'),
        ('Backward', 'BOOL', '反向输出'),
        ('Done', 'BOOL', '动作完成'),
        ('Busy', 'BOOL', '运行中'),
        ('Error', 'BOOL', '故障'),
        ('Position', 'DINT', '当前位置(步数)'),
    ],
}

# FB 接口 (name, [ (类别, 参数, 类型, 注释) ... ])
FBS = {
    'FB_Debounce': [
        ('IN', 'RawIn', 'BOOL', '原始输入信号'),
        ('IN', 'FilterTime', 'DINT', '滤波时间(ms)'),
        ('OUT', 'FilteredOut', 'BOOL', '滤波后输出'),
        ('VAR', 'ton_Filter', 'TON', '滤波定时器'),
    ],
    'FB_AlarmLatch': [
        ('IN', 'FaultIn', 'BOOL', '故障源输入'),
        ('IN', 'Reset', 'BOOL', '复位命令(上升沿)'),
        ('OUT', 'Latched', 'BOOL', '故障锁存输出'),
        ('VAR', 'bLatched', 'BOOL', '锁存状态'),
        ('VAR', 'r_Fault', 'TRIG.R_TRIG', '故障边沿检测'),
    ],
    'FB_CmdHandshake': [
        ('IN', 'Cmd', 'BOOL', '命令输入(上升沿)'),
        ('IN', 'Done', 'BOOL', '完成反馈'),
        ('IN', 'Timeout', 'DINT', '超时时间(ms)'),
        ('IN', 'Abort', 'BOOL', '中止命令'),
        ('OUT', 'Latched', 'BOOL', '命令已锁存'),
        ('OUT', 'Busy', 'BOOL', '命令执行中'),
        ('OUT', 'Expired', 'BOOL', '超时标志'),
        ('OUT', 'Aborted', 'BOOL', '已中止标志'),
        ('VAR', 'bLatched', 'BOOL', '锁存状态'),
        ('VAR', 'bExpired', 'BOOL', '超时锁存'),
        ('VAR', 'bAborted', 'BOOL', '中止锁存'),
        ('VAR', 'r_Cmd', 'TRIG.R_TRIG', '命令边沿检测'),
        ('VAR', 'ton_Timeout', 'TON', '超时定时器'),
    ],
    'FB_TimedAction': [
        ('IN', 'Start', 'BOOL', '启动输入(上升沿)'),
        ('IN', 'Time', 'DINT', '动作时长(ms)'),
        ('IN', 'InPos', 'BOOL', '到位信号'),
        ('IN', 'Limit', 'BOOL', '限位信号'),
        ('OUT', 'Running', 'BOOL', '动作执行中'),
        ('OUT', 'Done', 'BOOL', '动作完成'),
        ('OUT', 'Terminated', 'BOOL', '限位终止'),
        ('VAR', 'bRunning', 'BOOL', '运行状态'),
        ('VAR', 'r_Start', 'TRIG.R_TRIG', '启动边沿检测'),
        ('VAR', 'ton_Time', 'TON', '动作定时器'),
    ],
    'FB_StepperDrive': [
        ('IN', 'ManForward', 'BOOL', '手动正向'),
        ('IN', 'ManBackward', 'BOOL', '手动反向'),
        ('IN', 'AutoForward', 'BOOL', '自动正向'),
        ('IN', 'AutoBackward', 'BOOL', '自动反向'),
        ('IN', 'Reset', 'BOOL', '故障复位'),
        ('IN', 'Stop', 'BOOL', '停止'),
        ('IN', 'Enable', 'BOOL', '运行许可'),
        ('OUT', 'Forward', 'BOOL', '正向输出'),
        ('OUT', 'Backward', 'BOOL', '反向输出'),
        ('OUT', 'Busy', 'BOOL', '运行中'),
        ('OUT', 'Done', 'BOOL', '完成'),
        ('OUT', 'Error', 'BOOL', '故障'),
        ('VAR', 'bForward', 'BOOL', '正向状态'),
        ('VAR', 'bBackward', 'BOOL', '反向状态'),
        ('VAR', 'bError', 'BOOL', '故障状态'),
    ],
    'FB_Roller': [
        ('IN', 'RunFwd', 'BOOL', '正转启动'),
        ('IN', 'RunRev', 'BOOL', '反转启动'),
        ('IN', 'SpeedLevel', 'INT', '速度档(1/2/3)'),
        ('IN', 'SpeedLow', 'INT', '低速档(%)'),
        ('IN', 'SpeedMid', 'INT', '中速档(%)'),
        ('IN', 'SpeedHigh', 'INT', '高速档(%)'),
        ('OUT', 'A', 'BOOL', '方向A输出'),
        ('OUT', 'B', 'BOOL', '方向B输出'),
        ('OUT', 'Speed', 'INT', '速度值(%)'),
        ('VAR', 'bFwd', 'BOOL', '正转状态'),
        ('VAR', 'bRev', 'BOOL', '反转状态'),
    ],
    'FB_TowerLight': [
        ('IN', 'Fault', 'BOOL', '故障状态'),
        ('IN', 'Auto', 'BOOL', '自动模式'),
        ('IN', 'Manual', 'BOOL', '手动模式'),
        ('IN', 'RunOK', 'BOOL', '运行许可'),
        ('OUT', 'Red', 'BOOL', '红灯'),
        ('OUT', 'Yellow', 'BOOL', '黄灯'),
        ('OUT', 'Green', 'BOOL', '绿灯'),
        ('OUT', 'Buzzer', 'BOOL', '蜂鸣器'),
    ],
    'FB_EtherCAT_Axis_ST': [
        ('INOUT', 'Axis', '_sMCAXIS_INFO', '轴句柄'),
        ('IN', 'PowerEnable', 'BOOL', '轴使能'),
        ('IN', 'Stop', 'BOOL', '轴停止'),
        ('IN', 'Reset', 'BOOL', '故障复位'),
        ('IN', 'Home', 'BOOL', '回零启动'),
        ('IN', 'JogForward', 'BOOL', '正向点动'),
        ('IN', 'JogBackward', 'BOOL', '反向点动'),
        ('IN', 'Jogvelocity', 'REAL', '点动速度'),
        ('IN', 'JogAcceleration', 'REAL', '点动加速度'),
        ('IN', 'JogDeceleration', 'REAL', '点动减速度'),
        ('IN', 'Absolute_Execute', 'BOOL', '绝对定位启动'),
        ('IN', 'Absolute_Position', 'REAL', '目标位置'),
        ('IN', 'Absolute_Velocity', 'REAL', '定位速度'),
        ('IN', 'Absolute_Acceleration', 'REAL', '定位加速度'),
        ('IN', 'Absolute_Deceleration', 'REAL', '定位减速度'),
        ('IN', 'Timeout', 'DINT', '定位超时时间(ms), 0=不启用'),
        ('OUT', 'AxisStatusData', 'AxisStatusData', '轴状态结构'),
        ('OUT', 'Absolute_MoveAbsoluteDone', 'BOOL', '绝对定位完成'),
        ('OUT', 'Absolute_Expired', 'BOOL', '绝对定位超时到期'),
        ('VAR', 'fb_Power', 'MC_Power', '使能功能块'),
        ('VAR', 'fb_Reset', 'MC_Reset', '复位功能块'),
        ('VAR', 'fb_Stop', 'MC_Stop', '停止功能块'),
        ('VAR', 'fb_Home', 'MC_Home', '回零功能块'),
        ('VAR', 'fb_Jog', 'MC_JOG', '点动功能块'),
        ('VAR', 'fb_MoveAbsolute', 'MC_MoveAbsolute', '绝对定位功能块'),
        ('VAR', 'fb_ReadStatus', 'MC_ReadStatus', '读轴状态功能块'),
        ('VAR', 'fb_ReadAxisError', 'MC_ReadAxisError', '读轴故障功能块'),
        ('VAR', 'r_HomeStart', 'TRIG.R_TRIG', '回零启动边沿'),
        ('VAR', 'r_HomeDone', 'TRIG.R_TRIG', '回零完成边沿'),
        ('VAR', 'r_AbsStart', 'TRIG.R_TRIG', '定位启动边沿'),
        ('VAR', 'ton_AbsTimeout', 'TON', '定位超时定时器'),
        ('VAR', 'bAbsTiming', 'BOOL', '定位计时中标志'),
        ('VAR', 'bErrorStop', 'BOOL', '错误停止状态'),
        ('VAR', 'bDisabled', 'BOOL', '轴断使能状态'),
        ('VAR', 'bStopping', 'BOOL', '停止中状态'),
        ('VAR', 'bStandStill', 'BOOL', '静止状态'),
        ('VAR', 'bDiscreteMotion', 'BOOL', '离散运动状态'),
        ('VAR', 'bContinuousMotion', 'BOOL', '连续运动状态'),
        ('VAR', 'bSyncMotion', 'BOOL', '同步运动状态'),
        ('VAR', 'bHoming', 'BOOL', '回零中状态'),
    ],
}

# con 内部控制变量 (name, type, address, 注释) — 通用
CON_VARS = [
    ('con_EstopPressed', 'BOOL', 'D2000', '急停按下标志(常闭取反)'),
    ('con_Heart_Counter', 'INT', 'D2001', '心跳记忆值(看门狗)'),
    ('con_CommLost', 'BOOL', 'D2002', '通讯丢失标志'),
    ('con_ErrorID', 'DINT', 'D2003', '故障位编码(bit0~bit9)'),
    ('con_ErrorBit', 'BOOL', 'D2004', '总故障位'),
    ('con_RunOK', 'BOOL', 'D2005', '运行许可(急停OK且无故障且通讯正常)'),
    ('con_AllHomed', 'BOOL', 'D2006', '4轴全部回零完成'),
    ('con_ManualEnable', 'BOOL', 'D2007', '手动模式使能'),
    ('con_AutoEnable', 'BOOL', 'D2008', '自动模式使能'),
    ('con_ModeChanged', 'BOOL', 'D2009', '模式切换沿'),
    ('con_Mode_Prev', 'BOOL', 'D2010', '模式上周期值'),
    ('con_RollerFwd_Manual', 'BOOL', 'D2011', '辊筒手动正转'),
    ('con_RollerRev_Manual', 'BOOL', 'D2012', '辊筒手动反转'),
    ('con_RollerRun_Auto', 'BOOL', 'D2013', '辊筒自动运行(上位机)'),
    ('con_RollerDir_Auto', 'BOOL', 'D2014', '辊筒自动方向'),
    ('con_RollerRun_Total', 'BOOL', 'D2015', '辊筒总运行(手动OR自动)'),
    ('con_RollerDir_Total', 'BOOL', 'D2016', '辊筒总方向'),
    ('con_RollerSpeed_Total', 'INT', 'D2017', '辊筒总速度档'),
    ('con_TimeoutAlarm', 'BOOL', 'D2018', '动作超时报警(锁存输出)'),
    ('con_Scan_Step', 'INT', 'D2019', '扫描步标记'),
    ('con_TimeoutReq', 'BOOL', 'D2020', '超时检测源(SBR_06置位, SBR_03锁存)'),
    ('con_AlarmReset', 'BOOL', 'D2021', '报警复位命令(上升沿, 接本地/HMI复位)'),
    ('con_Heart_Prev', 'INT', 'D2022', '入向心跳上周期值(变化判在线)'),
    ('con_CommDegraded', 'BOOL', 'D2023', '通讯降级(冻结新命令,已锁存动作继续完成)'),
    ('con_LastCmdSeq', 'INT', 'D2024', '上次受理命令序号(防无线重放)'),
    ('con_HeartQ', 'BOOL', 'D2025', '出向心跳周期到标志(TONR直调Q)'),
    ('con_HeartRst', 'BOOL', 'D2026', '出向心跳定时器复位脉冲'),
]

# 按原型追加的变量 (自动生成, 不进 JSON 规格单)
#   con: (name, type, 注释) — 地址由生成器在 CON_VARS 后顺延
#   host: (var_name, data_type, 注释, direction) — 地址由生成器在 comm_reg 后顺延
#   inst: (name, type, 注释)
ARCHETYPE_EXTRA = {
    'internal_seq': {
        'con': [
            ('con_Step_No', 'INT', '当前工步步号'),
            ('con_StepRun', 'BOOL', '步状态机运行'),
            ('con_Step_Init', 'BOOL', '步状态机初始化/回零'),
            ('con_Start', 'BOOL', '自动启动'),
            ('con_Stop', 'BOOL', '自动停止'),
            ('con_TimeoutQ', 'BOOL', '定位超时瞬时标志(TONR直调Q, 工步间复用)'),
        ],
        'host': [
            ('host_Send_Start', 'INT', '自动启动(=1)', 'write'),
            ('host_Send_Stop', 'INT', '自动停止(=1)', 'write'),
            ('host_Send_Home', 'INT', '自动回零(=1)', 'write'),
            ('host_Rcv_Step_No', 'INT', '当前工步号', 'read'),
            ('host_Rcv_StepRun', 'INT', '步状态机运行', 'read'),
        ],
        'inst': [
            ('r_StepFwd', 'TRIG.R_TRIG', '手动单步边沿检测'),
        ],
    },
}

# HMI 手动变量 (按设备推导, 通用)
#   servo: hmi_JogP_M{n} / hmi_JogN_M{n}   BOOL, S 地址
#   stepper: hmi_StepP_{eng} / hmi_StepN_{eng}   BOOL, S 地址
#   roller: hmi_Roller_Fwd / hmi_Roller_Rev   BOOL, S 地址
HMI_BASE = 200   # hmi BOOL 起始 S 地址 (S200)

# 共享常量 (每个工程自动带, 不进规格单)  (name, type, value, 注释)
SHARED_CONST = [
    ('AXIS_STATE_OFF', 'DINT', '0', '轴状态: 断使能'),
    ('AXIS_STATE_ERRORSTOP', 'DINT', '1', '轴状态: 错误停止'),
    ('AXIS_STATE_STOPPING', 'DINT', '2', '轴状态: 停止中'),
    ('AXIS_STATE_STANDSTILL', 'DINT', '3', '轴状态: 静止'),
    ('AXIS_STATE_DISCRETE', 'DINT', '4', '轴状态: 离散运动'),
    ('AXIS_STATE_CONTINUOUS', 'DINT', '5', '轴状态: 连续运动'),
    ('AXIS_STATE_SYNC', 'DINT', '6', '轴状态: 同步'),
    ('AXIS_STATE_HOMING', 'DINT', '7', '轴状态: 回零'),
]

